services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network

  redis:
    image: redis:7-alpine
    container_name: redis_db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - database_network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - database_network

  rustfs:
    image: rustfs/rustfs:1.0.0-glibc
    container_name: rustfs
    restart: unless-stopped
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
        RUSTFS_ACCESS_KEY: rustfsadmin
        RUSTFS_SECRET_KEY: rustfsadmin
    volumes:
        - ./rustfs_data:/data
    command: server /data --console-address ":9001"
    networks:
        - database_network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  database_network:
    driver: bridge
